apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: debug
spec:
  containers:
  - name: debug
    image: anill146/debug:1.0.0
